name: Configure Azure environment

on:      
  pull_request:
    types: [labeled]
  workflow_dispatch:
env:
  IMAGE_REGISTRY_URL: ghcr.io
  AZURE_RESOURCE_GROUP: cd-with-actions
  AZURE_APP_PLAN: actions-ttt-deployment
  AZURE_LOCATION: East US
  AZURE_WEBAPP_NAME: idreesjanib1-ttt-app

jobs:
  setup-azure-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure resource group
        run: |
          az group create --location "${{ env.AZURE_LOCATION }}" --name "${{ env.AZURE_RESOURCE_GROUP }}"

     
  destroy-azure-resources:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'destroy environment')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Destroy Azure environment
        run: |
          az group delete --name "${{ env.AZURE_RESOURCE_GROUP }}" --yes --no-wait
